/*
 ******************************************************************************
 File:     main.cpp
 Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2019-03-13

 The MIT License (MIT)
 Copyright (c) 2018 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */

#include "stm32f10x_DWT.h"
#include "stm32f10x.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_gpio.h"
#include "stm32f1xx_it.h"
#include "FreeRTOS.h"
#include "task.h"

GPIO_InitTypeDef gpioInitStruct;

extern "C" void SetupRunTimeStatsTimer(void)
{
	/* Set interrupt priority and enable TIMER7 interrupt in NVIC */

	NVIC_SetPriority(TIM4_IRQn, NVIC_PriorityGroup_0);
	NVIC_EnableIRQ(TIM4_IRQn);

	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);
	TIM_TimeBaseInitTypeDef TimBaseStruct;

	TimBaseStruct.TIM_Prescaler = 0x1194;
	TimBaseStruct.TIM_Period = 0x1;
	TIM_TimeBaseInit(TIM4, &TimBaseStruct);
	TIM_ITConfig(TIM4, TIM_IT_Update, ENABLE);

	TIM_Cmd(TIM4, ENABLE);
}

void delay(unsigned int nCount)
{
	unsigned int i, j;

	for (i = 0; i < nCount; i++)
		for (j = 0; j < 0x2AFF; j++)
			;
}

volatile unsigned long ulHighFrequencyTimerTicks = 0;

extern "C" void TIM4_IRQHandler(void)
{
	/* Clear the pending bit in NVIC and TIMER7 */
	NVIC_ClearPendingIRQ(TIM4_IRQn);
	TIM_ClearITPendingBit(TIM4, TIM_IT_Update);

	/* Increment the counter used to mease execution time */
	ulHighFrequencyTimerTicks++;
}

void ledBlinkTask(void* pv)
{
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC, ENABLE);

	gpioInitStruct.GPIO_Pin = GPIO_Pin_13;
	gpioInitStruct.GPIO_Speed = GPIO_Speed_2MHz;
	gpioInitStruct.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_Init(GPIOC, &gpioInitStruct);

	while (1)
	{
		/* Toggle LED on PA0 */
		// Reset bit will turn on LED (because the logic is interved)
		GPIO_ResetBits(GPIOC, GPIO_Pin_13);
		delay(250);
		// Set bit will turn off LED (because the logic is interved)
		GPIO_SetBits(GPIOC, GPIO_Pin_13);
		delay(250);
	}
}

void task2(void* pv)
{
	while (1)
	{
		vTaskDelay(1);
	}
}

int main()
{
	xTaskCreate(ledBlinkTask, (const char*) "Ledsignal Task", 128, NULL, 1,
			NULL);
	xTaskCreate(task2, (const char*) "Task 2", 128, NULL, 1, NULL);

	vTaskStartScheduler();

	while (1)
		;

	return 0;
}

